/*
 * Automatically generated C config: don't edit
 * Linux kernel version: KERNELVERSION
 * Sat Dec  5 04:47:00 2015
 */
#define AUTOCONF_INCLUDED
#define CONFIG_SOC_PARAMS 1
#define CONFIG_MACH ci20
#define CONFIG_NEED_INTERRUPT_STACK 1
#define CONFIG_EXCEPTION_STACK_SIZE 4096
#define CONFIG_ARCH mips
#define CONFIG_SOFTIRQ 1
#define CONFIG_HAS_SMP 1
#define CONFIG_JTAG_ENABLE 1
#define CONFIG_BITS 32
#define CONFIG_BOOT 1
#define CONFIG_INTERRUPT_STACK_SIZE 4096
#define CONFIG_ABI_EABI 1
#define CONFIG_MACH_PARAMS 1
#define CONFIG_INITCALL 1
#define CONFIG_GC_SECTIONS 1
#define CONFIG_WAIT_BROKEN 1
#define CONFIG_MACH_CI20 1
#define CONFIG_CPU_MIPS32R2 1
#define CONFIG_TEXT_OFFSET 0x00010000
#define CONFIG_STACK_ALIGNMENT 16
#define CONFIG_LOG_NOTE 1
#define CONFIG_NR_THREAD_PRIORITY 32
#define CONFIG_MIPS32 1
#define CONFIG_HZ 32768
#define CONFIG_STARTUP_STACK_SIZE 4096
#define CONFIG_ARCH_MIPS 1
#define CONFIG_LOG_LEVEL LOG_LEVEL_NOTE
#define CONFIG_SOC_JZ4780 1
#define CONFIG_PHYS_ADDR 0x80000000
#define CONFIG_VIRT_ADDR 0x80000000
#define CONFIG_CPU_HAS_SYNC 1
#define CONFIG_ENDIAN_LITTLE 1
#define CONFIG_BUG 1
#define CONFIG_PHYS_SIZE 0x10000000
#define CONFIG_SOC jz4780
#define CONFIG_DSR 1
#define CONFIG_SMP 1
#define CONFIG_CROSS_COMPILE mips-none-elf-
